### PR TITLE
enable auto allcoated network tests

### PR DESCRIPTION
**Pull request by SeanMooney**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1681
Related: [OSPRH-6541](https://issues.redhat.com//browse/OSPRH-6541)

### CODE REVIEW

**Review by slawqo — APPROVED** [review]

**Comment by SeanMooney** [comment]
ill drop the hold once the depency merges.
tide wont wait for that otherwise

**Comment by SeanMooney** [comment]
check-rdo
zuul was restarted

**Comment by SeanMooney** [comment]
https://github.com/openstack-k8s-operators/ci-framework/pull/1681 is now merged

**Pull request merged**
