### PR TITLE
Use the new lib-common/common/log interface

### PR DESCRIPTION
**Pull request by gibizer**
It is a Draft as only the nova controller is switched over to the new interface. 

Depends-on: https://github.com/openstack-k8s-operators/lib-common/pull/125

### CODE REVIEW

**Review by bogdando — CHANGES_REQUESTED** [review]
So if I get the comments for dependency patch correct, we should rework this to just use log.FromContext(ctx) ?

**Comment by bogdando** [comment]
> So if I get the comments for dependency patch correct, we should rework this to just use log.FromContext(ctx) ?

please disregard... that's exaclty what you are already doing here :)

**Review by bogdando — APPROVED** [review]

**Comment by stuggi** [comment]
@bogdando not sure if you wanted to merge this ?

**Comment by bogdando** [comment]
No, I've missed that auto-merge feature. All I wanted is to remove the "requires changes" mark set by me earlier :(

**Comment by bogdando** [comment]
Shall we revert or wait for https://github.com/openstack-k8s-operators/lib-common/pull/125 to become merged. Sorry for unexpected auto-merge

**Pull request merged**
