### PR TITLE
Bump golang to 1.21

### PR DESCRIPTION
**Pull request by mrkisaolamb**
Jira: [OSPRH-9448](https://issues.redhat.com//browse/OSPRH-9448)
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/911

### CODE REVIEW

**Comment by gibizer** [comment]
The meta-content-provider failing on golang conflict 

```
2024-09-16 11:47:03.603343 | controller | TASK [operator_build : nova-operator - Call manifests dry_run={{ cifmw_operator_build_dryrun|bool }}, chdir={{ operator.src }}, output_dir={{ cifmw_operator_build_basedir }}/artifacts, script=make manifests] ***
2024-09-16 11:47:03.603351 | controller | Monday 16 September 2024  11:46:35 -0400 (0:00:00.033)       0:02:35.833 ******
2024-09-16 11:47:03.603364 | controller | Follow script's output here: /home/zuul/ci-framework-data/logs/ci_script_001_nova_operator_call.log
2024-09-16 11:47:03.603372 | controller | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
2024-09-16 11:47:03.603378 | controller | fatal: [localhost]: FAILED! => changed=true
2024-09-16 11:47:03.603387 | controller |   msg: non-zero return code
2024-09-16 11:47:03.603395 | controller |   rc: 2
2024-09-16 11:47:03.603404 | controller |   stderr: ''
2024-09-16 11:47:03.603412 | controller |   stderr_lines: <omitted>
2024-09-16 11:47:03.603420 | controller |   stdout: |-
2024-09-16 11:47:03.603427 | controller |     ~/src/github.com/openstack-k8s-operators/nova-operator ~/ci-framework-data/artifacts
2024-09-16 11:47:03.603435 | controller |     test -f go.work || go work init
2024-09-16 11:47:03.603443 | controller |     go work use .
2024-09-16 11:47:03.603449 | controller |     go work use ./api
2024-09-16 11:47:03.603455 | controller |     go work sync
2024-09-16 11:47:03.603461 | controller |     go: downloading github.com/openstack-k8s-operators/lib-common/modules/common v0.4.1-0.20240905123813-174296c09ec6
2024-09-16 11:47:03.603467 | controller |     go: downloading github.com/openstack-k8s-operators/keystone-operator/api v0.4.1-0.20240730210414-ba2309d261a2
2024-09-16 11:47:03.603473 | controller |     go: downloading github.com/openstack-k8s-operators/lib-common/modules/test v0.4.1-0.20240730142703-7fd3da600c9d
2024-09-16 11:47:03.603481 | controller |     go: downloading github.com/onsi/ginkgo v1.16.5
2024-09-16 11:47:03.603489 | controller |     go: downloading github.com/openstack-k8s-operators/infra-operator/apis v0.4.1-0.20240730162859-91b64b2d2de7
2024-09-16 11:47:03.603497 | controller |     go: downloading github.com/openstack-k8s-operators/mariadb-operator/api v0.4.1-0.20240730222151-2d771bf1a024
2024-09-16 11:47:03.603522 | controller |     go: downloading github.com/openstack-k8s-operators/lib-common/modules/openstack v0.4.1-0.20240730142703-7fd3da600c9d
2024-09-16 11:47:03.603536 | controller |     go: downloading github.com/openshift/api v0.0.0-20240830023148-b7d0481c9094
2024-09-16 11:47:03.603562 | controller |     go: downloading github.com/evanphx/json-patch v4.12.0+incompatible
2024-09-16 11:47:03.603571 | controller |     go: downloading github.com/google/gnostic-models v0.6.8
2024-09-16 11:47:03.603578 | controller |     go: downloading github.com/davecgh/go-spew v1.1.1
2024-09-16 11:47:03.603586 | controller |     go: downloading github.com/pmezard/go-difflib v1.0.0
2024-09-16 11:47:03.603593 | controller |     go: downloading github.com/rogpeppe/go-internal v1.11.0
2024-09-16 11:47:03.603601 | controller |     go: downloading github.com/emicklei/go-restful v2.10.0+incompatible
2024-09-16 11:47:03.603621 | controller |     go: downloading github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
2024-09-16 11:47:03.603631 | controller |     go: version constraints conflict:
2024-09-16 11:47:03.603662 | controller |             github.com/openstack-k8s-operators/infra-operator/apis@v0.4.1-0.20240730162859-91b64b2d2de7 requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603674 | controller |             github.com/openstack-k8s-operators/keystone-operator/api@v0.4.1-0.20240730210414-ba2309d261a2 requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603683 | controller |             github.com/openstack-k8s-operators/lib-common/modules/common@v0.4.1-0.20240905123813-174296c09ec6 requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603691 | controller |             github.com/openstack-k8s-operators/lib-common/modules/openstack@v0.4.1-0.20240730142703-7fd3da600c9d requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603699 | controller |             github.com/openstack-k8s-operators/mariadb-operator/api@v0.4.1-0.20240730222151-2d771bf1a024 requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603706 | controller |     go: version constraints conflict:
2024-09-16 11:47:03.603714 | controller |             github.com/openstack-k8s-operators/lib-common/modules/common@v0.4.1-0.20240905123813-174296c09ec6 requires github.com/evanphx/json-patch@v5.6.0+incompatible, but github.com/evanphx/json-patch@v4.12.0+incompatible is requested
2024-09-16 11:47:03.603722 | controller |     make: *** [Makefile:362: gowork] Error 1
2024-09-16 11:47:03.603729 | controller |   stdout_lines: <omitted>
```

**Comment by stuggi** [comment]
maybe have to get https://github.com/openstack-k8s-operators/install_yamls/pull/911 landed first since ci_framework still installing 1.20

https://logserver.rdoproject.org/60/860/b5839c12203f0a463e9e1acb34fdd8d14f4b49e5/github-check/openstack-meta-content-provider/fb46eb5/ci-framework-data/logs/ci_script_000_run_download.log

```
TASK [download_tools : Download and extract golang src=https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz, dest=/usr/local, remote_src=True, extra_opts=['--exclude', 'go/misc', '--exclude', 'go/pkg/linux_amd64_race', '--exclude', 'go/test']] ***
Monday 16 September 2024  11:03:55 -0400 (0:00:01.005)       0:00:12.917 ****** 
[0;33mchanged: [localhost] => changed=true [0m
[0;33m  dest: /usr/local[0m
[0;33m  extract_results:[0m
[0;33m    cmd:[0m
[0;33m    - /bin/gtar[0m
[0;33m    - --extract[0m
[0;33m    - -C[0m
[0;33m    - /usr/local[0m
[0;33m    - -z[0m
[0;33m    - --show-transformed-names[0m
[0;33m    - --exclude[0m
[0;33m    - go/misc[0m
[0;33m    - --exclude[0m
[0;33m    - go/pkg/linux_amd64_race[0m
[0;33m    - --exclude[0m
[0;33m    - go/test[0m
[0;33m    - -f[0m
[0;33m    - /home/zuul/.ansible/tmp/ansible-tmp-1726499035.2887366-30547-203819378487302/go1.20.14.linux-amd64vuxqz8pz.tar.gz[0m
[0;33m    err: ''[0m
[0;33m    out: ''[0m
[0;33m    rc: 0[0m
[0;33m  gid: 0[0m
[0;33m  group: root[0m
[0;33m  handler: TgzArchive[0m
[0;33m  mode: '0755'[0m
[0;33m  owner: root[0m
[0;33m  secontext: system_u:object_r:usr_t:s0[0m
[0;33m  size: 141[0m
[0;33m  src: /home/zuul/.ansible/tmp/ansible-tmp-1726499035.2887366-30547-203819378487302/go1.20.14.linux-amd64vuxqz8pz.tar.gz[0m
[0;33m  state: directory[0m
[0;33m  uid: 0[0m
```

Not sure if a Depends-On would work.

**Comment by mrkisaolamb** [comment]
Ok I rerun tests with depends on

**Comment by stuggi** [comment]
fyi, I added the dep to install_yamls which uses 1.21 in https://github.com/openstack-k8s-operators/infra-operator/pull/276 - https://softwarefactory-project.io/zuul/t/rdoproject.org/build/aabccfb388904f6b9196962dca63222e . 
It solved this issue with the json-patch version dep, but it failed with 

```
go: go.work requires go >= 1.21.13 (running go 1.21.11; GOTOOLCHAIN=local)
```

When testing local, what worked is to keep the local golang in sync with the go version from [registry.access.redhat.com/ubi9/go-toolset:1.21](http://registry.access.redhat.com/ubi9/go-toolset:1.21) .
Still checking if we setting the toolchain version in go.mod, or GOTOOLCHAIN env is an option

**Comment by stuggi** [comment]
> fyi, I added the dep to install_yamls which uses 1.21 in [openstack-k8s-operators/infra-operator#276](https://github.com/openstack-k8s-operators/infra-operator/pull/276) - https://softwarefactory-project.io/zuul/t/rdoproject.org/build/aabccfb388904f6b9196962dca63222e . It solved this issue with the json-patch version dep, but it failed with
> 
> ```
> go: go.work requires go >= 1.21.13 (running go 1.21.11; GOTOOLCHAIN=local)
> ```
> 
> When testing local, what worked is to keep the local golang in sync with the go version from [registry.access.redhat.com/ubi9/go-toolset:1.21](http://registry.access.redhat.com/ubi9/go-toolset:1.21) . Still checking if we setting the toolchain version in go.mod, or GOTOOLCHAIN env is an option

The issue with this is that if golang outside and inside the build container it fails with the above. The reason for this is that we first create the go.work files and afterwards in the container build via the Dockerfile we copy the src into. Part of that are the go.work/go.work.sum files which would have the go version from outside. We should remove the go.work files from the copied source, like in https://github.com/openstack-k8s-operators/infra-operator/pull/276/commits/ac9d213e3cbf0363e12926693023c1783614263d

We still need to get the openstack-operator pr landed first.

**Comment by mrkisaolamb** [comment]
recheck

**Comment by mrkisaolamb** [comment]
recheck

**Comment by stuggi** [comment]
for the `Build operator without publishing it` job you'd also have to bump go version in https://github.com/openstack-k8s-operators/nova-operator/blob/main/.github/workflows/build-operator-dont-publish.yaml#L17

**Review by dprince — APPROVED** [review]

**Review by gibizer — APPROVED** [review]

**Pull request merged**
