### PR TITLE
[tempest]Reduce running tests

### PR DESCRIPTION
**Pull request by gibizer**
Only run the api tests for compute and scenario tests.

### CODE REVIEW

**Comment by gibizer** [comment]
/hold
I see strange tempest failures where test remaining inprogress and the tempest exits with error. I guess there is a global timeout somewhere we started to hit. Let's see if I reduce the number of test cases then we can be below that limit

**Comment by gibizer** [comment]
the tempest part of the run in this PR took 38 minutes, on main it takes 49 minutes and fails.

**Comment by gibizer** [comment]
/unhold
test reduction helpes the tempest test run in now 38 (down from 49) minutes

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Pull request merged**
