### PR TITLE
Disable cpu power management by default

### PR DESCRIPTION
**Pull request by gibizer**
We have multiple issue with power management so we disable it again.

Related: https://issues.redhat.com/browse/OSPRH-8806
Related: https://issues.redhat.com/browse/OSPRH-8712

### CODE REVIEW

**Comment by gibizer** [comment]
recheck we need to spend time stabilizing the local storage job as it fails a lot intermittently recently.

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
now that #828 merge we have a chance to get a green CI here.

**Comment by gibizer** [comment]
/unhold

We agreed over Slack that due to the topology issue causing NUMA resource accounting issues even if we fix the governor issue quickly we cannot go out with power mgmt enabled by default.

**Review by SeanMooney — APPROVED** [review]
approving this based on the proximity to ga

we will move the default to on to bugfix 1 or later once the upstream bugs are resolved and backported

we will also document in a know issue releasnote how this fucntioantly can be used safely without the bugfix via the govoner policy.

we do not want to default to the governer policy because it has an inherent upgrade impact.

we can enable this by default in a later release.

**Pull request merged**
