### PR TITLE
Run make bundle and commit the diff

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by yazug** [comment]
looks like this should clear things up, thanks!

**Comment by SeanMooney** [comment]
im not sure if we should be holding this until after the beta freeze

**Review by SeanMooney — APPROVED** [review]
appoving but we will hold till after beta

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
/unhold
beta freeze is over

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Pull request merged**
