### PR TITLE
Add missing local webhooks

### PR DESCRIPTION
**Pull request by abays**
I missed these in the recent webhooks follow-up.

### CODE REVIEW

**Comment by abays** [comment]
I'm not sure how these changes for local webhooks could have affected Tempest testing, since the local webhooks would not be in use there.  Retrying.

/test nova-operator-build-deploy-tempest

**Comment by gibizer** [comment]
the first failed tempest test case:
```
{14} tempest.api.compute.limits.test_absolute_limits_negative.AbsoluteLimitsNegativeTestJSON.test_max_metadata_exceed_limit [32.409456s] ... FAILED
```
tempest.log
```
2023-05-22 10:29:40.578 156 INFO tempest.lib.common.rest_client [-] Request (AbsoluteLimitsNegativeTestJSON:test_max_metadata_exceed_limit): 504 POST http://nova-public-openstack.apps.oko-11.oooci.ccitredhat.com/v2.1/servers 30.059s
```
related nova-api log
```
[pod/nova-api-0/nova-api-log] 2023-05-22 10:29:13.153 12 DEBUG nova.api.openstack.wsgi [None req-5984a7bd-6bdb-4c3a-8145-29e9a6a75c0e 5e924d2666af4796b9aed2df35f165b4 e3f5585611c5465e8ba48f9fd0bbbe37 - - default default] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7fa9055dba60>>, body: {"server": {"name": "tempest-AbsoluteLimitsNegativeTestJSON-server-749428800", "imageRef": "446d5e0a-8165-4322-ab65-ba18ae5bffa2", "flavorRef": "280fbac6-75af-4661-b05d-a733f72e9975", "metadata": {"0": "0", "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "10": "10", "11": "11", "12": "12", "13": "13", "14": "14", "15": "15", "16": "16", "17": "17", "18": "18", "19": "19", "20": "20", "21": "21", "22": "22", "23": "23", "24": "24", "25": "25", "26": "26", "27": "27", "28": "28", "29": "29", "30": "30", "31": "31", "32": "32", "33": "33", "34": "34", "35": "35", "36": "36", "37": "37", "38": "38", "39": "39", "40": "40", "41": "41", "42": "42", "43": "43", "44": "44", "45": "45", "46": "46", "47": "47", "48": "48", "49": "49", "50": "50", "51": "51", "52": "52", "53": "53", "54": "54", "55": "55", "56": "56", "57": "57", "58": "58", "59": "59", "60": "60", "61": "61", "62": "62", "63": "63", "64": "64", "65": "65", "66": "66", "67": "67", "68": "68", "69": "69", "70": "70", "71": "71", "72": "72", "73": "73", "74": "74", "75": "75", "76": "76", "77": "77", "78": "78", "79": "79", "80": "80", "81": "81", "82": "82", "83": "83", "84": "84", "85": "85", "86": "86", "87": "87", "88": "88", "89": "89", "90": "90", "91": "91", "92": "92", "93": "93", "94": "94", "95": "95", "96": "96", "97": "97", "98": "98", "99": "99", "100": "100", "101": "101", "102": "102", "103": "103", "104": "104", "105": "105", "106": "106", "107": "107", "108": "108", "109": "109", "110": "110", "111": "111", "112": "112", "113": "113", "114": "114", "115": "115", "116": "116", "117": "117", "118": "118", "119": "119", "120": "120", "121": "121", "122": "122", "123": "123", "124": "124", "125": "125", "126": "126", "127": "127", "128": "128"}}} _process_stack /usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py:511
[pod/nova-api-0/nova-api-log] 2023-05-22 10:30:06.005 12 DEBUG nova.api.openstack.wsgi_app [-] ******************************************************************************** log_opt_values /usr/lib/python3.9/site-packages/oslo_config/cfg.py:2589
[pod/nova-api-0/nova-api-log] 2023-05-22 10:30:06.005 12 DEBUG nova.api.openstack.wsgi_app [-] Configuration options gathered from: log_opt_values /usr/lib/python3.9/site-packages/oslo_config/cfg.py:2590
[pod/nova-api-0/nova-api-log] 2023-05-22 10:30:06.006 12 DEBUG nova.api.openstack.wsgi_app [-] command line args: [] log_opt_values /usr/lib/python3.9/site-packages/oslo_config/cfg.py:2591
```
So it seems the nova-api pod crashed / restarted.

Based on the pod status the probes are timed out and therefore k8s restarted the pod. 
```
Warning  Unhealthy       2m41s (x2 over 2m52s)  kubelet            Liveness probe failed: Get "http://10.128.0.179:8774/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       2m36s (x6 over 3m2s)   kubelet            Readiness probe failed: Get "http://10.128.0.179:8774/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       2m36s (x6 over 3m2s)   kubelet            Readiness probe failed: Get "http://10.128.0.179:8774/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       2m31s (x3 over 2m52s)  kubelet            Liveness probe failed: Get "http://10.128.0.179:8774/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

This is not related to the PR it is related to the fact that nova-api at the moment handles only a single API request at a given time. And if there is a longer running request then a parallel probe can time out.

**Comment by gibizer** [comment]
I try to poke the tempest issue in a separate PR https://github.com/openstack-k8s-operators/nova-operator/pull/381

**Review by gibizer — APPROVED** [review]
looks good

**Pull request merged**
