### PR TITLE
Enable CPU power management by default for libvirt compute

### PR DESCRIPTION
**Pull request by gibizer**
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/591 (to pick up a new tcib) (merged)
Implementes: https://issues.redhat.com/browse/OSPRH-83

### CODE REVIEW

**Comment by gibizer** [comment]
The nova-compute service fails to start :/
```
2023-11-16 10:42:42.444 2 ERROR oslo_service.service [None req-56dbf76c-524c-455d-9c64-d3474509e8d0 - - - - - -] Error starting thread.: nova.exception.InvalidConfiguration: '[compute]/cpu_dedicated_set' is mandatory to be set if '[libvirt]/cpu_power_management' is set.Please provide the CPUs that can be pinned or don't use the power management if you only use shared CPUs.
2023-11-16 10:42:42.444 2 ERROR oslo_service.service Traceback (most recent call last):
2023-11-16 10:42:42.444 2 ERROR oslo_service.service   File "/usr/lib/python3.9/site-packages/oslo_service/service.py", line 806, in run_service
2023-11-16 10:42:42.444 2 ERROR oslo_service.service     service.start()
2023-11-16 10:42:42.444 2 ERROR oslo_service.service   File "/usr/lib/python3.9/site-packages/nova/service.py", line 162, in start
2023-11-16 10:42:42.444 2 ERROR oslo_service.service     self.manager.init_host(self.service_ref)
2023-11-16 10:42:42.444 2 ERROR oslo_service.service   File "/usr/lib/python3.9/site-packages/nova/compute/manager.py", line 1608, in init_host
2023-11-16 10:42:42.444 2 ERROR oslo_service.service     self.driver.init_host(host=self.host)
2023-11-16 10:42:42.444 2 ERROR oslo_service.service   File "/usr/lib/python3.9/site-packages/nova/virt/libvirt/driver.py", line 831, in init_host
2023-11-16 10:42:42.444 2 ERROR oslo_service.service     libvirt_cpu.power_down_all_dedicated_cpus()
2023-11-16 10:42:42.444 2 ERROR oslo_service.service   File "/usr/lib/python3.9/site-packages/nova/virt/libvirt/cpu/api.py", line 122, in power_down_all_dedicated_cpus
2023-11-16 10:42:42.444 2 ERROR oslo_service.service     raise exception.InvalidConfiguration(msg)
2023-11-16 10:42:42.444 2 ERROR oslo_service.service nova.exception.InvalidConfiguration: '[compute]/cpu_dedicated_set' is mandatory to be set if '[libvirt]/cpu_power_management' is set.Please provide the CPUs that can be pinned or don't use the power management if you only use shared CPUs.
```

**Comment by SeanMooney** [comment]
this is a bug in nova which we should fix.
it should be a noop when cpu_dedicated_set is not defiend.

**Comment by gibizer** [comment]
Waiting for the upstream fix land in Antelope 	
Allow enabling cpu_power_management with 0 dedicated CPUs

**Comment by gibizer** [comment]
The upstream nova fix merged in 2023.1[1] we just need to wait for the tcib image to be built

[1] https://review.opendev.org/c/openstack/nova/+/901660

**Comment by gibizer** [comment]
> The upstream nova fix merged in 2023.1[1] we just need to wait for the tcib image to be built. (need a newer tcib than 03a7b1adc9a02f73bcd7593e55c1d943)
> 
> [1] https://review.opendev.org/c/openstack/nova/+/901660

We have a fresh nova-compute image to try https://quay.io/repository/podified-antelope-centos9/openstack-nova-compute/manifest/sha256:53728912e768f56b124c39955e322e61fa54fc5aa2f701535ae13108a11ade2b

**Comment by gibizer** [comment]
recheck 
timeout
```
{1} tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_hotplug_nic [] ... inprogress
```

**Comment by gibizer** [comment]
recheck

```
Details: Host list [{'zone': 'nova', 'host_name': 'compute-1.ci-rdo.local'}, {'zone': 'nova', 'host_name': 'compute-0.ci-rdo.local'}] is shorter than min_compute_nodes. Did a compute worker not boot correctly?
```
Spot on tempest. The 3rd compute cannot connect to the message bus:
```
2023-12-08 13:11:42.521 2 ERROR oslo.messaging._drivers.impl_rabbit [None req-eba3ba3c-6dd7-400c-bcb1-67df26e778ff - - - - - -] Connection failed: [Errno 113] EHOSTUNREACH (retrying in 1.0 seconds): OSError: [Errno 113] EHOSTUNREACH
```
https://review.rdoproject.org/zuul/build/0854d0debc304970b42a17dfc108eb47/log/controller/ci-framework-data/logs/192.168.122.102/log/containers/nova/nova-compute.log

This is a new type of instability that two out of three computes can connect but not the thirs.

**Comment by gibizer** [comment]
recheck 
see if tempest is faster than 49minutes during the weekend or if during the weekend it the overall deploy is faster

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Pull request merged**
