### PR TITLE
Add --vebose to host discover

### PR DESCRIPTION
**Pull request by gibizer**
The nova cell controller runs nova-manage cell_v2 discover_hosts
in a Job when a new compute's statefulset becomes ready. This PR just
adds --verbose to the command to get more information about the mapped
computes.

### CODE REVIEW

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Review by bogdando — COMMENTED** [review]
this aligns with that other places and docs refer. As a side note, those other places do not mention the --by-service flag, howeveer

**Comment by gibizer** [comment]
> this aligns with that other places and docs refer. As a side note, those other places do not mention the --by-service flag, howeveer

For ironic computes using --by-service is recommended https://github.com/openstack/nova/blob/master/releasenotes/notes/discover-hosts-by-service-06ee20365b895127.yaml And we only support ironic compute (and fake) with the NovaCompute CR and therefore with this host discovery logic.

**Comment by gibizer** [comment]
recheck zuul was restarted and running jobs was lost

**Comment by gibizer** [comment]
recheck retry limit

**Comment by gibizer** [comment]
recheck tempest seems to be slower in the ceph job

**Comment by gibizer** [comment]
Timing of a passed ceph job:
```
2024-06-11 14:49:13.286965 | controller | ===============================================================================
2024-06-11 14:49:13.286973 | controller | test_operator : Wait for the last job to be Completed - tempest ------ 5328.48s
2024-06-11 14:49:13.286981 | controller | edpm_deploy : Wait for OpenStackDataPlaneDeployment become Ready ----- 1122.56s
2024-06-11 14:49:13.287008 | controller | edpm_deploy : Wait for OpenStackDataPlaneDeployment become Ready ------ 584.19s
2024-06-11 14:49:13.287015 | controller | edpm_prepare : Wait for OpenStack controlplane to be deployed --------- 326.13s
2024-06-11 14:49:13.287021 | controller | edpm_prepare : Wait for OpenStack operator to get installed ----------- 242.62s
2024-06-11 14:49:13.287027 | controller | install_yamls_makes : Run openstack ----------------------------------- 166.35s
2024-06-11 14:49:13.287033 | controller | openshift_setup : Wait for openshift-marketplace pods to be running ---- 71.27s
2024-06-11 14:49:13.287039 | controller | cifmw_cephadm : Run cephadm bootstrap ---------------------------------- 65.54s
2024-06-11 14:49:13.287046 | controller | cifmw_cephadm : Wait for expected number of osds to be running --------- 63.38s
2024-06-11 14:49:13.287052 | controller | edpm_prepare : Wait for OpenStack subscription creation ---------------- 61.26s
2024-06-11 14:49:13.287058 | controller | run_hook : Run 82 Kustomize and update Control Plane ------------------- 33.95s
2024-06-11 14:49:13.287064 | controller | test_operator : Wait for the test-operator csv to Succeed -------------- 32.94s
2024-06-11 14:49:13.287070 | controller | edpm_prepare : Wait for control plane to change its status ------------- 30.06s
2024-06-11 14:49:13.287076 | controller | run_hook : Run Download needed tools ----------------------------------- 29.53s
2024-06-11 14:49:13.287158 | controller | cifmw_cephadm : Apply ceph rgw keystone config ------------------------- 28.93s
2024-06-11 14:49:13.287196 | controller | test_operator : Wait until the test-operator csv is present ------------ 24.16s
2024-06-11 14:49:13.287202 | controller | ci_setup : Install needed packages ------------------------------------- 22.31s
2024-06-11 14:49:13.287208 | controller | cifmw_cephadm : Configure object store to use rgw ---------------------- 19.04s
2024-06-11 14:49:13.287214 | controller | cert_manager : Wait for cert-manager pods to be ready ------------------ 12.16s
2024-06-11 14:49:13.287220 | controller | cifmw_cephadm : Apply spec --------------------------------------------- 11.86s
2024-06-11 18:49:28.468962 | controller | changed
```
Timing of a passed non ceph job:
```
2024-06-12 03:47:09.422435 | controller | Wednesday 12 June 2024  03:47:09 -0400 (0:00:00.010)       1:47:53.768 ********
2024-06-12 03:47:09.422442 | controller | ===============================================================================
2024-06-12 03:47:09.422448 | controller | test_operator : Wait for the last job to be Completed - tempest ------ 3717.42s
2024-06-12 03:47:09.422454 | controller | edpm_deploy : Wait for OpenStackDataPlaneDeployment become Ready ----- 1504.57s
2024-06-12 03:47:09.422460 | controller | edpm_prepare : Wait for OpenStack controlplane to be deployed --------- 368.69s
2024-06-12 03:47:09.422473 | controller | edpm_prepare : Wait for OpenStack operator to get installed ----------- 270.93s
2024-06-12 03:47:09.422479 | controller | install_yamls_makes : Run openstack ----------------------------------- 171.51s
2024-06-12 03:47:09.422485 | controller | openshift_setup : Wait for openshift-marketplace pods to be running ---- 71.30s
2024-06-12 03:47:09.422491 | controller | edpm_prepare : Wait for OpenStack subscription creation ---------------- 61.45s
2024-06-12 03:47:09.422497 | controller | test_operator : Wait until the test-operator csv is present ------------ 35.29s
2024-06-12 03:47:09.422503 | controller | edpm_prepare : Wait for control plane to change its status ------------- 30.08s
2024-06-12 03:47:09.422515 | controller | ci_setup : Install needed packages ------------------------------------- 28.13s
2024-06-12 03:47:09.422521 | controller | run_hook : Run Download needed tools ----------------------------------- 25.85s
2024-06-12 03:47:09.422527 | controller | test_operator : Wait for the test-operator csv to Succeed -------------- 22.16s
2024-06-12 03:47:09.422533 | controller | cert_manager : Wait for cert-manager pods to be ready ------------------ 12.05s
2024-06-12 03:47:09.422571 | controller | install_yamls_makes : Run netconfig_deploy ----------------------------- 10.14s
2024-06-12 03:47:09.422577 | controller | repo_setup : Initialize python venv and install requirements ------------ 7.99s
2024-06-12 03:47:09.422584 | controller | run_hook : Run Tune rabbitmq resources ---------------------------------- 6.36s
2024-06-12 03:47:09.422696 | controller | edpm_deploy : Run nova-manage discover_hosts to ensure compute nodes are mapped --- 6.36s
2024-06-12 03:47:09.422707 | controller | install_yamls_makes : Run edpm_deploy_prep ------------------------------ 6.11s
2024-06-12 03:47:09.422713 | controller | ci_local_storage : Perform action in the PV directory ------------------- 5.96s
2024-06-12 03:47:09.422720 | controller | test_operator : Ensure that the test-operator-logs-pod is Running ------- 5.76s
2024-06-12 07:47:24.756812 | controller | changed
2024-06-12 07:47:24.836921 | 
```

**Comment by gibizer** [comment]
recheck ceph job timed out

**Comment by gibizer** [comment]
/test functional
A new instability 
```
2024-06-12T22:36:13.274Z	INFO	Controllers.NovaAPI	Deployment is not ready	{"controller": "novaapi", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaAPI", "NovaAPI": {"name":"8023b615-8551-4fea-88cf-9-api","namespace":"ed3280cd-9121-40b0-8caa-552be476a7d1"}, "namespace": "ed3280cd-9121-40b0-8caa-552be476a7d1", "name": "8023b615-8551-4fea-88cf-9-api", "reconcileID": "e802553e-ce65-4047-9d63-30f3b8b60608", "Status": {"observedGeneration":1,"replicas":1,"readyReplicas":1,"availableReplicas":0}}
718
  2024-06-12T22:36:13.274Z	INFO	Controllers.NovaAPI	Waiting for the Deployment to become Ready before exposing the service in Keystone	{"controller": "novaapi", "controllerGroup": "nova.openstac

...

  [FAILED] Timed out after 20.001s.
793
  The function passed to Eventually failed at /go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator/api@v0.3.1-0.20240605055850-8ee0ece70906/test/helpers/crd.go:240 with:
794
  Expected success, but got an error:
795
      <*errors.StatusError | 0xc000dd7b80>: 
796
      keystoneendpoints.keystone.openstack.org "nova" not found
797
      {
798
          ErrStatus: {
799
              TypeMeta: {Kind: "", APIVersion: ""},
800
              ListMeta: {
801
                  SelfLink: "",
802
                  ResourceVersion: "",
803
                  Continue: "",
804
                  RemainingItemCount: nil,
805
              },
806
              Status: "Failure",
807
              Message: "keystoneendpoints.keystone.openstack.org \"nova\" not found",
808
              Reason: "NotFound",
809
              Details: {
810
                  Name: "nova",
811
                  Group: "keystone.openstack.org",
812
                  Kind: "keystoneendpoints",
813
                  UID: "",
814
                  Causes: nil,
815
                  RetryAfterSeconds: 0,
816
              },
817
              Code: 404,
818
          },
819
      }
820
  In [It] at: /go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator/api@v0.3.1-0.20240605055850-8ee0ece70906/test/helpers/crd.go:241 @ 06/12/24 22:36:33.133
821
822
  Full Stack Trace
823
    github.com/openstack-k8s-operators/keystone-operator/api/test/helpers.(*TestHelper).GetKeystoneEndpoint(0xc0003d1878, {{0xc00173a7e0?, 0xc000f78b98?}, {0x1ffce56?, 0x1f0a1e0?}})
824
    	/go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator/api@v0.3.1-0.20240605055850-8ee0ece70906/test/helpers/crd.go:241 +0x1c3
825
    github.com/openstack-k8s-operators/keystone-operator/api/test/helpers.(*TestHelper).SimulateKeystoneEndpointReady.func1({0x2324668, 0xc000a067e0})
826
    	/go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator/api@v0.3.1-0.20240605055850-8ee0ece70906/test/helpers/crd.go:254 +0x46
827
    reflect.Value.call({0x1c72dc0?, 0xc000a067b0?, 0x41490a?}, {0x1ffc7ae, 0x4}, {0xc00176b800, 0x1, 0x5c?})
828
    	/usr/lib/golang/src/reflect/value.go:586 +0xb07
829
    reflect.Value.Call({0x1c72dc0?, 0xc000a067b0?, 0xc00006a000?}, {0xc00176b800?, 0x25ef39647955?, 0x1f0a1e0?})
830
    	/usr/lib/golang/src/reflect/value.go:370 +0xbc
831
    github.com/onsi/gomega/internal.(*AsyncAssertion).buildActualPoller.func3()
832
    	/go/pkg/mod/github.com/onsi/gomega@v1.33.1/internal/async_assertion.go:325 +0x13a
833
    github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc0004bfab0, {0x230d030?, 0x332cc50}, 0x1, {0x0, 0x0, 0x0})
834
    	/go/pkg/mod/github.com/onsi/gomega@v1.33.1/internal/async_assertion.go:398 +0x18c
835
    github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc0004bfab0, {0x230d030, 0x332cc50}, {0x0, 0x0, 0x0})
836
    	/go/pkg/mod/github.com/onsi/gomega@v1.33.1/internal/async_assertion.go:145 +0x8d
837
    github.com/openstack-k8s-operators/keystone-operator/api/test/helpers.(*TestHelper).SimulateKeystoneEndpointReady(0xc0003d1878, {{0xc00173a7e0, 0x24}, {0x1ffce56, 0x4}})
838
    	/go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator/api@v0.3.1-0.20240605055850-8ee0ece70906/test/helpers/crd.go:257 +0x190
839
    github.com/openstack-k8s-operators/nova-operator/test/functional.glob..func4.10({{0xc00173a7e0?, 0x0?}, {0x201769b?, 0x0?}})
840
    	/go/src/github.com/openstack-k8s-operators/operator/test/functional/nova_controller_test.go:1131 +0x107d
841
    github.com/openstack-k8s-operators/mariadb-operator/api/test/helpers.(*MariaDBTestHarness).RunBasicSuite.func1.3()
842
    	/go/pkg/mod/github.com/openstack-k8s-operators/mariadb-operator/api@v0.3.1-0.20240604125710-954ab886bb52/test/helpers/harnesses.go:154 +0xad
```

**Pull request merged**
