### PR TITLE
Refactor tests to always cleanup namespaces

### PR DESCRIPTION
**Pull request by SeanMooney**
This change refactors the test helpers to return
errors and moved asserts to the test cases instead.

### CODE REVIEW

**Comment by gibizer** [comment]
This still does not clean up the Namespace when run locally. :/ I suspect something is about [garbage collections](https://book.kubebuilder.io/reference/envtest.html#testing-considerations)

```
$ git diff
diff --git a/test/functional/novaapi_controller_test.go b/test/functional/novaapi_controller_test.go
index 9387ab8..a015049 100644
--- a/test/functional/novaapi_controller_test.go
+++ b/test/functional/novaapi_controller_test.go
@@ -83,5 +83,9 @@ var _ = Describe("NovaAPI controller", func() {
                        }, timeout, interval).Should(
                                HaveField("Status", corev1.ConditionUnknown))
                })
+
+               It("...", func() {
+                       Expect(true).To(BeTrue())
+               })
        })
 })
$ make test
test -s /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin/controller-gen || GOBIN=/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
test -s /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin/setup-envtest || GOBIN=/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
KUBEBUILDER_ASSETS="/home/gibi/.local/share/kubebuilder-envtest/k8s/1.24.2-linux-amd64" go test ./... -coverpkg=./controllers -coverprofile cover.out
?   	github.com/openstack-k8s-operators/nova-operator	[no test files]
?   	github.com/openstack-k8s-operators/nova-operator/controllers	[no test files]
Running Suite: Controller Suite - /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional
===============================================================================================================
Random Seed: 1664025893

Will run 2 of 2 specs
•
------------------------------
• [FAILED] [0.004 seconds]
NovaAPI controller [BeforeEach]
/home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:45
  when A NovaAPI CR instance is created without any input
  /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:74
    ...
    /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:87

  Expected
      <*errors.StatusError | 0xc0005d6be0>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "object is being deleted: namespaces \"test-namespace\" already exists",
              Reason: "AlreadyExists",
              Details: {
                  Name: "test-namespace",
                  Group: "",
                  Kind: "namespaces",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
  to be nil
  In [BeforeEach] at: /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:47
------------------------------


Summarizing 1 Failure:
  [FAIL] NovaAPI controller [BeforeEach] when A NovaAPI CR instance is created without any input ...
  /home/gibi/upstream/git/openstack-k8s-operators/nova-operator/test/functional/novaapi_controller_test.go:47

Ran 2 of 2 Specs in 6.422 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestAPIs (6.42s)
FAIL
coverage: 44.4% of statements in ./controllers
FAIL	github.com/openstack-k8s-operators/nova-operator/test/functional	6.437s
FAIL
make: *** [Makefile:108: test] Error 1
```

**Comment by SeanMooney** [comment]
https://book.kubebuilder.io/reference/envtest.html#namespace-usage-limitation
its proably specificaly related to that part ya

can i suggest that we either check if we are unsign an existing instance and if we are not we generate a uuid
and append that to the namespace or always create a random namepace as that suggests.

fyi the reasom im checking this while im off i i wanted to see if the operator could be run on my arm m1 macbook air. the answer is yes and enve test "works" there too :)

ill look into the namespace change on monday
let me know which way you would prefer to go. always random or based on if using an exsiting cluster?

**Comment by gibizer** [comment]
> https://book.kubebuilder.io/reference/envtest.html#namespace-usage-limitation its proably specificaly related to that part ya
> 
> can i suggest that we either check if we are unsign an existing instance and if we are not we generate a uuid and append that to the namespace or always create a random namepace as that suggests.

locally I went with the random namespace thing. I still want to keep the test cases separated so I don't want to ever reuse a namespace.
> 
> fyi the reasom im checking this while im off i i wanted to see if the operator could be run on my arm m1 macbook air. the answer is yes and enve test "works" there too :)

Nice! :)

> 
> ill look into the namespace change on monday let me know which way you would prefer to go. always random or based on if using an exsiting cluster?

**Comment by SeanMooney** [comment]
gibi worked around this and refactored the tests while i was off and we have merged that version now so closing this as its not needed anymore

**Pull request closed without merging**
