### PR TITLE
enable srbac by default

### PR DESCRIPTION
**Pull request by gibizer**
This change enables nova's srbac feature
including scope enforcement

Closes: [OSPRH-1505](https://issues.redhat.com//browse/OSPRH-1505)

### CODE REVIEW

**Comment by gibizer** [comment]
just to troubleshoot #626 as we suspect it might be related to github Id

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
/hold
lets decide between #626 or #627

**Comment by gibizer** [comment]
recheck
I don't see exact the kuttl job failure in the lgos

**Comment by gibizer** [comment]
recheck

I see keystone 500 responses in the tempest log
```
    raise exceptions.IdentityError(
tempest.lib.exceptions.IdentityError: Got identity error
Details: Unexpected status code 500
```
But there is no must gather available :/
```
When opening a support case, bugzilla, or issue please include the following summary data along with any other requested information:
[must-gather      ] OUT Using must-gather plug-in image: quay.io/openstack-k8s-operators/openstack-must-gather:latest
error getting cluster version: Unauthorized
ClusterID: 
ClusterVersion: Installing "" for <unknown>: <unknown>
error getting cluster operators: Unauthorized
ClusterOperators:
	clusteroperators are missing
```

**Comment by gibizer** [comment]
This is @SeanMooney's patch I just cherry-picked it as we have a small issue in CI with CamelCase github IDs which is fixed separately. But until then Sean's cannot pass CI.

**Review by SeanMooney — APPROVED** [review]
i am working on fixing the ci issue but approving this via gibi submitting it to complete it for this quarter

**Pull request merged**
