### PR TITLE
Disable HTTP2 in webhooks

### PR DESCRIPTION
**Pull request by dprince**
Also bumps golang.org/x/net to v0.17.0

Jira: [OSPRH-468](https://issues.redhat.com//browse/OSPRH-468)

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by gibizer** [comment]
It seems the kuttl env is broken on dev-preview2. Should we ignore it and forcemerge?
```


2023-11-09 07:01:50.551785 \| TASK [install kuttl test_suite dependencies]
--
1587 | 2023-11-09 02:01:51.083691 \| controller \| make: go: No such file or directory
1588 | 2023-11-09 02:01:51.134356 \| controller \| oc apply -k test/kuttl/test-suites/default/deps/ --timeout=120s
1589 | 2023-11-09 02:01:51.137730 \| controller \| bash: line 1: oc: command not found
1590 | 2023-11-09 02:01:51.138027 \| controller \| make: *** [Makefile:364: kuttl-test-prep] Error 127
1591 | 2023-11-09 07:02:22.014594 \| controller \| ERROR
1592 | 2023-11-09 07:02:22.014793 \| controller \| {
1593 | 2023-11-09 07:02:22.014843 \| controller \|   "attempts": 3,
1594 | 2023-11-09 07:02:22.014880 \| controller \|   "delta": "0:00:00.064935",
1595 | 2023-11-09 07:02:22.014912 \| controller \|   "end": "2023-11-09 02:02:21.973328",
1596 | 2023-11-09 07:02:22.014945 \| controller \|   "msg": "non-zero return code",
1597 | 2023-11-09 07:02:22.014976 \| controller \|   "rc": 2,
1598 | 2023-11-09 07:02:22.015007 \| controller \|   "start": "2023-11-09 02:02:21.908393"
1599 | 2023-11-09 07:02:22.015038 \| controller \| }


```

**Comment by gibizer** [comment]
and no prow jobs are triggered :/

**Comment by gibizer** [comment]
kuttl fix merged on dev-preview2, so hopefully this will be green after the rebase

**Review by gibizer — APPROVED** [review]
The kuttl job passed (not reported yet) so this look good to me.

**Pull request merged**
