### PR TITLE
Use lib-common template to remove continuous empty lines

### PR DESCRIPTION
**Pull request by auniyal61**
Opting to remove extra lines from nova confs

### CODE REVIEW

**Comment by auniyal61** [comment]
/retest 
'error: timed out waiting for the condition on openstackcontrolplanes/controlplane'

**Comment by gibizer** [comment]
If you look at the functional test results you will see the following errors.
```
  2024-10-15T02:17:52.050Z	ERROR	Reconciler error	{"controller": "novanovncproxy", "controllerGroup": "nova.openstack.org", "controllerKind": "NovaNoVNCProxy", "NovaNoVNCProxy": {"name":"efe14c21-09aa-4716-9a4b-3-cell1-novncproxy","namespace":"8ba7c046-dcec-4fcb-8ca8-d44df168fcfb"}, "namespace": "8ba7c046-dcec-4fcb-8ca8-d44df168fcfb", "name": "efe14c21-09aa-4716-9a4b-3-cell1-novncproxy", "reconcileID": "5cd8be1d-cd14-4bcf-be98-6aa1f7bad0eb", "error": "template: tmp:344: function \"execTempl\" not defined"}
```
This is because even even though the lib-common change has been merged the given lib-common version is not used by this patch so the new templating function is not available. You need to bump the lib-common version in the go.mod files to point to the latest commit from the lib-common repo.

**Review by gibizer — COMMENTED** [review]
Looks good. Let's wait for the CI results.

**Comment by gibizer** [comment]
Generated config looks good https://softwarefactory-project.io/zuul/t/rdoproject.org/build/eeac0621d3d447e49f7e05a49493a2b3/log/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/secrets/nova/nova-cell1-compute-config.yaml-01-nova.conf

**Review by gibizer — APPROVED** [review]

**Pull request merged**
