### PR TITLE
Remove external-compute samples

### PR DESCRIPTION
**Pull request by booxter**
UPD:

    They are obsolete and not used anywhere. If we ever need something
    similar for CI purposes, we will have to effectively start from
    scratch anyway.

---

ORIGINAL DESCRIPTION:

Setting it is no longer needed since ovn role will configure sb connection strings in metadata agent and ovn-controller via ConfigMaps / Secrets prepared by neutron and ovn operators.

NOTE: I don't know if this sample is current at all. If this is not helpful, let me know and I will abandon the PR. Thanks.

### CODE REVIEW

**Comment by gibizer** [comment]
> Setting it is no longer needed since ovn role will configure sb connection strings in metadata agent and ovn-controller via ConfigMaps / Secrets prepared by neutron and ovn operators.
> 
> NOTE: I don't know if this sample is current at all. If this is not helpful, let me know and I will abandon the PR. Thanks.

I think the whole external-compute directory can be dropped now as they are heavily outdated and is no test fails they are unused.

**Comment by SeanMooney** [comment]
ya we can drop them
i woudl like to reintrodce a similar set of examples as part of ci jobs but we don't need the current ones

**Comment by booxter** [comment]
Ack. I killed the whole subdirectory as you suggested.

**Comment by booxter** [comment]
```
oc project cert-manager-operator
error: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~)

```

**Comment by booxter** [comment]
recheck

**Review by SeanMooney — APPROVED** [review]

**Pull request merged**
