### PR TITLE
[envtest]Use keystone helpers from keystone-operator

### PR DESCRIPTION
**Pull request by gibizer**
This was necessary to remove a dependency cycle from lib-common

### CODE REVIEW

**Comment by gibizer** [comment]
/unhold
dependencies landed

**Comment by gibizer** [comment]
you can test that it does not depend on the lib-common keystone helpers any more by adding the following replace and run the test locally. The lib-common hash there is the one that removes the keystone helpers from lib-common (https://github.com/openstack-k8s-operators/lib-common/pull/339)
```
replace github.com/openstack-k8s-operators/lib-common/modules/test => github.com/gibizer/lib-common/modules/test v0.0.0-20230925122035-657099e5679d
```

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
