### PR TITLE
Revert "Make the ceph job non voting until fixed"

### PR DESCRIPTION
**Pull request by gibizer**
This reverts commit 31755a17b55bfc14022a8fd5ad3309ee8e37804a.

### CODE REVIEW

**Comment by gibizer** [comment]
Let's land this as soon as we can make ceph  job passing again.

**Comment by gibizer** [comment]
rebased, the fixes for the ceph job have been landed.

**Comment by gibizer** [comment]
recheck

**Review by mrkisaolamb — APPROVED** [review]
lgtm

**Pull request merged**
