### PR TITLE
compute firewall

### PR DESCRIPTION
**Pull request by SeanMooney**
add vnc firewall config

Related: [OSPRH-85](https://issues.redhat.com//browse/OSPRH-85)
Closes: [OSPRH-222](https://issues.redhat.com//browse/OSPRH-222)

### CODE REVIEW

**Comment by mrKisaoLamb** [comment]
@SeanMooney not fully related question, but in tripleo I saw that also ports used in live migration are added to the rules. Should we do this here also? (for tripleo it was range 61152-61215)

**Comment by gibizer** [comment]
> is that what 61152-61215 is I did not see documentation of that so I did not add it. I'm not sure why we need a port range for live migration beyond port 22.
> 
> I would prefer to do that in a follow-up pr specific for enabling cold/live migration supprot.

I agree let's add that when we see the need for it

**Comment by gibizer** [comment]
```
[root@edpm-compute-1 ~]# podman exec -it nova_compute /bin/bash
bash-5.1$ id
uid=42436(nova) gid=42436(nova) groups=42436(nova),59(tss),107(qemu),42400(kolla),42473(libvirt)
```

```
[root@edpm-compute-1 ~]# podman exec -it nova_compute /bin/bash
bash-5.1$ ls /var/lib/nova
compute_id  instances
bash-5.1$ ls -alh /var/lib/nova
total 8.0K
drwxr-x---. 4 nova nova 76 Jul  5 15:46 .
drwxr-xr-x. 1 root root 23 Jul  5 15:38 ..
-rw-------. 1 nova nova  3 Jul  5 15:46 .bash_history
drwxr-x---. 3 nova nova 32 Jul  5 15:38 .cache
-rwxr-x---. 1 nova nova 36 Jul  5 15:39 compute_id
drwxr-x---. 4 nova nova 32 Jul  5 15:41 instances
bash-5.1$ ls -alh /var/lib/nova/instances/
_base/ locks/ 
bash-5.1$ ls -alh /var/lib/nova/instances/
total 0
drwxr-x---. 4 nova nova 32 Jul  5 15:41 .
drwxr-x---. 4 nova nova 76 Jul  5 15:46 ..
drwxr-xr-x. 2 nova nova 81 Jul  5 15:41 _base
drwxr-xr-x. 2 nova nova 91 Jul  5 15:41 locks
bash-5.1$ ls -alh /var/lib/nova/instances/_base/
total 32M
drwxr-xr-x. 2 nova nova   81 Jul  5 15:41 .
drwxr-x---. 4 nova nova   32 Jul  5 15:41 ..
-rw-r--r--. 1 nova nova 112M Jul  5 15:41 53da4918867d01f606506cf9d7d910bf88abd6fd
-rw-r--r--. 1 nova nova 1.0G Jul  5 15:41 ephemeral_1_0706d66
bash-5.1$ 
```

**Comment by SeanMooney** [comment]
if you restart the nova-compute does that fix it.

i think this might be a side effect of adding /var/lib/nova to the libvirt playbook in the previous pr

**Comment by gibizer** [comment]
> if you restart the nova-compute does that fix it.
> 

I've tried `podman restart nova_compute` but it did not solve the issue the next boot still fail with the same permission issue.

> i think this might be a side effect of adding /var/lib/nova to the libvirt playbook in the previous pr

**Comment by gibizer** [comment]
The fresh commit solves the /var/lib/nova permission issue. So I was able to also verify that the VNC proxy works now without the need for the manual firewall WA.

**Comment by gibizer** [comment]
Another data point. 
Without the change https://github.com/openstack-k8s-operators/nova-operator/commit/bf18bbe5d5ac1bb836ae6ad1df99bcecd7b49540#diff-2e4dd1d6efc4739db5315d75e3a6bf0121fd4c94549af7725177273158950895R17 the boot succeeds and the directory permissions are the followings:
```
[root@edpm-compute-1 ~]# ls -aln /var/lib/nova/
total 8
drwxr-xr-x.  4 42436 42436   55 Jul  6 08:26 .
drwxr-xr-x. 42     0     0 4096 Jul  6 08:26 ..
drwxr-xr-x.  3 42436 42436   32 Jul  6 08:26 .cache
-rw-r--r--.  1 42436 42436   36 Jul  6 08:26 compute_id
drwxr-xr-x.  5 42436 42436   76 Jul  6 08:41 instances
[root@edpm-compute-1 ~]# ls -aln /var/lib/nova/instances/
total 0
drwxr-xr-x. 5 42436 42436 76 Jul  6 08:41 .
drwxr-xr-x. 4 42436 42436 55 Jul  6 08:26 ..
drwxr-xr-x. 2 42436 42436 90 Jul  6 08:41 0b61f449-7678-4a41-ba5e-427a3d7a7233
drwxr-xr-x. 2 42436 42436 81 Jul  6 08:41 _base
drwxr-xr-x. 2 42436 42436 91 Jul  6 08:41 locks
[root@edpm-compute-1 ~]# ls -aln /var/lib/nova/instances/0b61f449-7678-4a41-ba5e-427a3d7a7233/
total 22500
drwxr-xr-x. 2 42436 42436       90 Jul  6 08:41 .
drwxr-xr-x. 5 42436 42436       76 Jul  6 08:41 ..
-rw-------. 1     0     0    69117 Jul  6 08:42 console.log
-rw-r--r--. 1   107   107 21364736 Jul  6 08:45 disk
-rw-r--r--. 1   107   107   485376 Jul  6 08:41 disk.config
-rw-r--r--. 1   107   107   393216 Jul  6 08:42 disk.eph0
-rw-r--r--. 1 42436 42436      162 Jul  6 08:41 disk.info
[root@edpm-compute-1 ~]# ls -aln /var/lib/nova/instances/_base/
226c8b2ef32fe8a368ead30f71dcfae27c90aa69  ephemeral_1_0706d66                       
[root@edpm-compute-1 ~]# ls -aln /var/lib/nova/instances/_base/
total 31748
drwxr-xr-x. 2 42436 42436         81 Jul  6 08:41 .
drwxr-xr-x. 5 42436 42436         76 Jul  6 08:41 ..
-rw-r--r--. 1   107   107  117440512 Jul  6 08:41 226c8b2ef32fe8a368ead30f71dcfae27c90aa69
-rw-r--r--. 1   107   107 1073741824 Jul  6 08:41 ephemeral_1_0706d66
[root@edpm-compute-1 ~]# 

```

**Comment by gibizer** [comment]
I think the relevant difference is:
```
good: drwxr-xr-x.  5 42436 42436   76 Jul  6 08:41 instances
bad:  drwxr-x---. 4 nova nova 32 Jul  5 15:41 instances
```

So with the current main the instances dir cannot be entered by `other` while in the working state it can be entered by `other`

**Comment by gibizer** [comment]
I think a fix would be to create the /var/lib/nova with 0755 mode if created from the libvirt playbook. 
```diff
diff --git a/playbooks/deploy-libvirt.yaml b/playbooks/deploy-libvirt.yaml
index 4dd64bd0..ed61a10a 100644
--- a/playbooks/deploy-libvirt.yaml
+++ b/playbooks/deploy-libvirt.yaml
@@ -14,7 +14,7 @@
       with_items:
       - { "path": /var/lib/openstack/config/libvirt}
       - { "path": /var/lib/openstack/config/containers}
-      - { 'path': /var/lib/nova}
+      - { "path": /var/lib/nova, "mode": "0755"}
       - { "path": /etc/tmpfiles.d/, "owner": "root", "group": "root"}
     - name: ensure /var/run/libvirt is present upon reboot
       become: true
```
The above make the instance boot work again.

**Review by gibizer — APPROVED** [review]
Works for me.

**Pull request merged**
