### PR TITLE
[envtest]Drop unused helper

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Review by mrKisaoLamb — APPROVED** [review]
lgtm

**Comment by gibizer** [comment]
/test nova-operator-build-deploy-tempest
slow node
```
++ oc get subscription openstack-operator -o 'jsonpath={.status.installedCSV}'
+ INSTALLED_CSV=openstack-operator.v0.0.1
+ oc get csv openstack-operator.v0.0.1 -o 'jsonpath={.spec.install.spec.deployments[*].name}'
+ timeout 240 xargs -I '{}' -d ' ' sh -c 'oc wait --for=condition=Available deployment {} --timeout=-1s'
Error from server (NotFound): deployments.apps "openstack-operator-controller-manager" not found
Error from server (NotFound): deployments.apps "dataplane-operator-controller-manager" not found
```

**Comment by gibizer** [comment]
recheck

```
2023-08-31 10:39:52.175525 \| controller \| /tmp/ensure_logged.sh: line 5: /usr/local/bin/oc: No such file or directory
--
662 | 2023-08-31 10:39:52.175751 \| controller \| Can not login to the CRC cluster. Sleeping...
663 | 2023-08-31 10:39:57.178651 \| controller \| /bin/sh: line 1: /usr/local/bin/oc: No such file or directory
```

**Comment by gibizer** [comment]
recheck
zuul CI issue is resolved

**Pull request merged**
