### PR TITLE
DNM: test ceph job

### PR DESCRIPTION
**Pull request by gibizer**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1757

### CODE REVIEW

**Comment by gibizer** [comment]
the ceph job still failing with the cert error
```
May 27 06:38:32 np0004677902 nova_compute[182231]: 2024-05-27 10:38:32.712 2 ERROR oslo.messaging._drivers.impl_rabbit [None req-55d7072e-4582-4676-a086-7fcd33e7683d - - - - - -] Connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129) (retrying in 1.0 seconds): ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)#033[00m
```

https://logserver.rdoproject.org/72/772/cdb60bb3ae7821ef6966a4fb14174c03db5426a5/github-check/nova-operator-tempest-multinode-ceph/fe05212/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/sos-reports/_all_nodes/sosreport-compute-0.ci-rdo.local/var/log/messages

**Comment by gibizer** [comment]
recheck

removed  https://github.com/openstack-k8s-operators/dataplane-operator/pull/896 from testing for now to see if 1757 alone helps or not.

**Comment by karelyatin** [comment]
> recheck
> 
> removed [openstack-k8s-operators/dataplane-operator#896](https://github.com/openstack-k8s-operators/dataplane-operator/pull/896) from testing for now to see if 1757 alone helps or not.

I don't think just using that patch will help considering issue was seen in other deployment where it's already set at https://github.com/openstack-k8s-operators/architecture/blob/e6930f5dfbb702cc6afd3d43c2245141c6b4605c/va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml#L28

I think would need also dataplane-operator PR + fixes as per comments there

**Comment by karelyatin** [comment]
recheck just to confirm

**Comment by karelyatin** [comment]
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://review.rdoproject.org/zuul/buildset/4d595c468fdd4b78842b9593ccd2f7e9
> 
> ❌ [openstack-k8s-operators-content-provider ](https://review.rdoproject.org/zuul/build/c590544d3fb54c6a8e2be39e21ac20f7) **FAILURE** in 11m 45s ⚠️ [nova-operator-kuttl ](https://review.rdoproject.org/zuul/build/97b54b5bc36b4faf8c1a125b9e30c511) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider ⚠️ [nova-operator-tempest-multinode ](https://review.rdoproject.org/zuul/build/387dc8740a1c4bf98256ab1a08951a0c) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider ⚠️ [nova-operator-tempest-multinode-ceph ](https://review.rdoproject.org/zuul/build/cb8c65bfe504468ebc79e7bf135d76ac) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider (non-voting)

content-provider job randomly fails at certmanager while running functional tests

**Comment by gibizer** [comment]
> > recheck
> > removed [openstack-k8s-operators/dataplane-operator#896](https://github.com/openstack-k8s-operators/dataplane-operator/pull/896) from testing for now to see if 1757 alone helps or not.
> 
> I don't think just using that patch will help considering issue was seen in other deployment where it's already set at https://github.com/openstack-k8s-operators/architecture/blob/e6930f5dfbb702cc6afd3d43c2245141c6b4605c/va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml#L28
> 
> I think would need also dataplane-operator PR + fixes as per comments there

So I run this before with 1757 and 896 together and it did not helped either. Now 1757 went into merge conflict so we cannot run with it.

Btw, in the meantime nova-operator made the ceph job non voting until it is fixed.

**Comment by slagle** [comment]
recheck

https://github.com/openstack-k8s-operators/ci-framework/pull/1757 is passing now with a depends-on https://github.com/openstack-k8s-operators/dataplane-operator/pull/896 so let's see if this one passes.

**Comment by slagle** [comment]
recheck

all depends-on have merged and https://review.rdoproject.org/zuul/builds?job_name=podified-multinode-hci-deployment-crc is now passing

**Comment by gibizer** [comment]
```
nova-operator-tempest-multinode-ceph (non-voting)
2 hrs 58 mins 39 secs
SUCCESS
```
So ceph is back to green again

**Pull request closed without merging**
