### PR TITLE
DNM:trigger tempest

### PR DESCRIPTION
**Pull request by gibizer**
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/482

### CODE REVIEW

**Comment by gibizer** [comment]
We have a metadata failure. https://logserver.rdoproject.org/85/585/0b6fc63dfd920d4890ad3a3b473c69d17c9af73f/github-check/nova-operator-tempest-multinode/018d11c/controller/ci-framework-data/tests/tempest/stestr_results.html 

I cannot reproduce it locally with install_yamls (everything seems to work there) but I see the same issue in the tempest job on openstack-operator. https://github.com/openstack-k8s-operators/openstack-operator/pull/539

**Comment by gibizer** [comment]
Lets see if https://github.com/openstack-k8s-operators/edpm-ansible/pull/482 solves it

**Comment by gibizer** [comment]
recheck

**Comment by booxter** [comment]
> Lets see if [openstack-k8s-operators/edpm-ansible#482](https://github.com/openstack-k8s-operators/edpm-ansible/pull/482) solves it

It did.

**Pull request closed without merging**
